### ISSUE TITLE
Wallet Tracking Issue

### ISSUE THREAD

**Issue by casey** [casey/ord#245]
- [x] `ord wallet init` – initialize a new wallet
- [x] `ord wallet fund` – get funding address
- [x] `ord wallet list` – list utxos in wallet
- [x] `ord wallet balance` – get wallet balance
- [x] `ord wallet identify` – show rare ordinals in wallet
- [x] `ord wallet send ORDINAL` – send the utxo an ordinal is in
- [x] set proper fee to transaction that sends an ordinal, see https://github.com/bitcoindevkit/bdk/issues/714
- [x] add rare ordinal protection to send
- [x] error if the ordinal you're sending would be consumed by fees
- [x] error if a special ordinal would be consumed by fees
- [ ] send minimal amount of sats (don't send whole utxo)
- [ ] `ord wallet recover` – recover a wallet from a given seed phrase (user types it in)
- [ ] let the user set the fee
- [ ] do dynamic fee estimation

**Comment by casey** [comment]
Closing this in favor of individual issues.
