### ISSUE TITLE
Collecting and trading tracking issue

### ISSUE THREAD

**Issue by raphjaph** [casey/ord#581]
- [x] `ord wallet identify`: show any rare ordinals in wallet
- [x] `ord wallet list`: list all ordinal ranges in contained in utxos controlled by bitcoincore wallet
- [ ] `ord wallet send ORDINAL ADDRESS`: send `ORDINAL` to `ADDRESS`
  - [x] send whole UTXO that contains ORDINAL to ADDRESS
  - [x] test that transaction building fails if ordinal isn't sent to address
  - [x] add `should_panic` tests for final checks
  - [x] rename `Template` to `TransactionBuilder`
  - [x] `Template::build_transaction` -> `TransactionBuilder::build`
  - [x]  move to own module
  - [x] test template to transaction conversion
  - [x] convert final tests to test transaction that is produced, not template
  - [x] pay fee
  - [x] Strip after ordinal if UTXO is larger than POSTAGE * 2, add change output to reduce POSTAGE to 1 x POSTAGE
  - [x] Align ordinal to beginning of sent output
  - [x] if ordinal would be lost in fee range, add input
  - [x] if utxo is insufficient to pay fee, add input
  - [x] if first output is below dust limit, add input
  - [x] check that no dust outputs are created
  - [x] display a good error message if we don't have enough padding inputs
  - [x] add invariant that each change address appears at most once in outputs
  - [x] add invariant that recipient address appears exactly once in outputs
  - [x] refuse to send if other rare ordinals would also be sent to recipient or be consumed by fee
  - [x] improve fee estimation
  - [ ] #692
  - [ ] #688
  - [ ] #691

**Comment by casey** [comment]
@raphjaph I just added a bunch of things that I had in a notes file. After the PR that we have in flight now, I think that almost all of these can be done in small follow-up PRs.

**Comment by casey** [comment]
I partially implemented refusing to send rare ordinals in #680. However, we still need to check that the utxo that we're sending doesn't contain any rare ordinals aside from the one we're sending. (If the user explicitly sends a rare ordinal, then we should assume they know what they're doing.)

**Comment by casey** [comment]
Closing in favor of individual issues. Nice work!
