### ISSUE TITLE
Beautification Tracking Issue

### ISSUE THREAD

**Issue by casey** [casey/ord#604]
- [ ] Show `value`, `address`, and `asm` on `/output` page #605
- [ ] Add height, timestamp, size, link to prev block, and weight to `/block` page #605 
- [ ] Display ranges with a hyphen #606 
- [ ] Consider making the second number in a range the last number in the range, and display single-ordinal ranges as just that ordinal #606 
- [ ] Dark mode #611 
- [ ] Show height, period, epoch, etc. on `/` #610 

Misc:
- [ ] refactor server error and option handling #607
- [ ] speed up tests #608
