### ISSUE TITLE
Rune tracking issue

### ISSUE THREAD

**Issue by casey** [casey/ord#627]
- [x] Publish rune to ordinals.com
- [x] Show rune on pages of inscribed ordinals
- [x] Link to ordinal from rune
- [ ] Write a chapter of the book on runes
- [ ] Finalize hashing algorithm
- [ ] Finalize metadata format #624 
- [ ] Include rune hash in transaction to establish "created before" date
- [ ] Show current address and utxo of ordinals
- [ ] Inscribe rune on range of ordinals
- [ ] Inscribe rune on multiple ranges of ordinals
- [ ] Inscribe rune on range of ordinals with step
- [ ] limit rune name to a-z
- [ ] Include media in rune that represents rune itself
- [ ] View all published runes at `/rune` or `/runes`
- [ ] Don't allow publishing runes with unknown fields
- [ ] Formalize or get rid of json representation
- [ ] Don't allow ordinal to be represented as anything but integer in rune
- [ ] Write a chapter of the book on ordinal and rune privacy
- [ ] Define consistent terminology for runes, merkle scripts, links, tokens, slots, assets, inscribed ordinals
- [ ] Include block hash in rune to establish "created after" date
- [ ] Include one or more pieces of media in rune that are assigned to inscrbied ordinals
- [ ] Sign rune with well-known public key
- [ ] Sign rune with pubkey of an ordinal and relationship (issuer "i made this", verifier "these details are correct", fan "i like this")
- [ ] When a rune is included in chain, have notion of issuing ordinal, which is an ordinal that participated in that transaction
- [ ] Consider numbering runes sequentially
- [ ] Consider representing runes with younger futhark
- [ ] Use `/BLOCK/TRANSACTION/INPUT` for slot notation, `/BLOCK/TRANSACTION` if first input in transaction, `/BLOCK` if in coinbase input. `SLOT.N` is Nth ordinal in rune
- [ ] Call them "paths" instead of slots
- [ ] Use `/BLOCK/TRANSACTION/INPUT/LEAF` so that a single taproot tree can commit to arbitrary many runes
- [ ] Resolve paths from root: `ordinals.com/BLOCK/TRANSACTION/INPUT/LEAF`
- [ ] Resolve paths to individual ordinals within rune with: `ordinals.com/BLOCK/TRANSACTION/INPUT/LEAF.OFFSET`
- [ ] Some way of giving runes nice names. Maybe first rune included in block with a given name.
- [ ] Define a text encoding for runes
- [ ] Accept runes by mail
- [ ] Explain rune scarcity
- [ ] consider using u64 or u128 for rune name and encoding in same way as ordinal name

**Comment by casey** [comment]
This is all too speculative for an issue.
