### ISSUE TITLE
Inscription Metadata

### ISSUE THREAD

**Issue by casey** [casey/ord#887]
This isn't really a single feature, but I want to collect current and future metadata fields in one place:

- [x] Type: MIME type that can be served as `Content-Type`
- [x] Resource: Payload bytes that can be served as HTTP resource
- [x] Magic number: Allow ord to skip non-ord containers, and allow protocol authors to utilize containers for other protocols
- [ ] Symbol: Human readable identifier for inscription #794 
- [ ] Encoding: String that can be served as `Content-Encoding` #891
- [ ] Link: Some kind of hash that can be used to look up off-chain content. #801 
- [ ] License: SHA-256 hash of content license. Not sure if this would be legally effective. #785
